//! Runtime assembly of MCP tool descriptions and server instructions from
//! three layers, so a deployment can extend what its agents are told without
//! a rebuild, an ssh session, or a container restart:
//!
//! 1. **Mechanics, always true** — compiled in via `include_str!` from
//!    `assets/mcp/server.md` and `assets/mcp/tools/<tool>.md`.
//! 2. **Mechanics, config-dependent** — short sentences this module emits
//!    from live config (e.g. [`retrieval_mode_sentence`]); the rest of that
//!    category (facet vocabularies, authoring rules) is generated by
//!    `server::build_instructions`, which sits between this module's two
//!    halves — see that function's caller in `server::run_server` for the
//!    exact composition order.
//! 3. **Per-KB policy** — markdown files loaded from the SERVED knowledge
//!    base (`mcp.extensions_path`) and appended last.
//!
//! Hard rule: the compiled layer (the `include_str!` constants below) may
//! only state what is true of EVERY knowledge base this binary will ever
//! serve — one process may serve a durable-reference KB and a scratch-space
//! KB at once. Per-KB policy belongs in the extension files, never here.
//! Extensions are APPEND-ONLY: they can never suppress or contradict a
//! compiled or config-derived sentence, only add to it.

use std::collections::HashMap;
use std::path::{Path, PathBuf};

use tracing::{debug, warn};

/// The six MCP tools this server exposes. Also the source of truth for which
/// `assets/mcp/tools/*.md` files must exist and which `tools/<tool>.md`
/// extension files a KB may provide.
pub const TOOL_NAMES: [&str; 6] = [
    "search",
    "get_document",
    "write_document",
    "delete_document",
    "get_schema",
    "update_schema",
];

/// Compiled-in server narrative — mechanics true of every KB this binary
/// could ever serve. See this module's doc comment for the hard rule that
/// keeps per-KB policy out of this file.
const SERVER_BASE: &str = include_str!("../assets/mcp/server.md");

/// Compiled-in per-tool base description, indexed by tool name. `None` for
/// any name outside [`TOOL_NAMES`].
fn compiled_tool_base(tool: &str) -> Option<&'static str> {
    match tool {
        "search" => Some(include_str!("../assets/mcp/tools/search.md")),
        "get_document" => Some(include_str!("../assets/mcp/tools/get_document.md")),
        "write_document" => Some(include_str!("../assets/mcp/tools/write_document.md")),
        "delete_document" => Some(include_str!("../assets/mcp/tools/delete_document.md")),
        "get_schema" => Some(include_str!("../assets/mcp/tools/get_schema.md")),
        "update_schema" => Some(include_str!("../assets/mcp/tools/update_schema.md")),
        _ => None,
    }
}

/// Cap on the body text taken from one KB extension file, in bytes. Keeps a
/// misbehaving or oversized document from ballooning a description that is
/// paid on every `tools/list` response. Truncated on a char boundary; a
/// truncation is logged via [`cap_extension_body`].
const MAX_EXTENSION_BODY_BYTES: usize = 8 * 1024;

/// The sentence appended to `search`'s description when quoted-phrase
/// matching is both configured (`search.phrase`) and actually available at
/// runtime (`status::INDEX_STATUS.phrase_matching_available()`) — callers
/// compute that combined `phrase_effective` flag the same way the search
/// handler does, then pass it to [`compose_tool_description`].
const PHRASE_SYNTAX_SENTENCE: &str =
    "Wrap a span in double quotes for an exact phrase match, e.g. `\"node:ares\"`.";

/// The config-derived sentence describing how `search` ranks results, for
/// each of the four `search.hybrid` x `search.phrase` combinations. This
/// replaces the compiled-in claim that used to live in `server.md` — that
/// claim was false whenever `hybrid` was off, since only the dense arm runs
/// then.
pub fn retrieval_mode_sentence(hybrid: bool, phrase: bool) -> &'static str {
    match (hybrid, phrase) {
        (true, true) => {
            "Search fuses literal term matching with semantic similarity, and a \
             double-quoted span matches as an exact phrase."
        }
        (true, false) => "Search fuses literal term matching with semantic similarity.",
        (false, true) => {
            "Search ranks by semantic similarity alone, except a double-quoted span, \
             which matches as an exact phrase."
        }
        (false, false) => "Search ranks by semantic similarity alone.",
    }
}

/// Join non-empty, trimmed sections with a blank line between them, then
/// trim the result's trailing whitespace. Shared by every composition
/// function so the append rule (blank line between sections, no trailing
/// whitespace) is enforced in exactly one place.
fn join_sections<'a>(sections: impl IntoIterator<Item = &'a str>) -> String {
    sections
        .into_iter()
        .map(str::trim)
        .filter(|s| !s.is_empty())
        .collect::<Vec<_>>()
        .join("\n\n")
}

/// The compiled server base plus the config-derived retrieval-mode sentence
/// — everything in categories 1 and 2 that does NOT depend on the live
/// corpus. `server::build_instructions` takes this as its `base` and appends
/// the corpus-dependent parts of category 2 (facet vocabularies, schema
/// scopes, authoring rules); the KB extension (category 3) is appended after
/// THAT, via [`append_extension`] — see this module's doc comment for the
/// full composition order.
pub fn compose_server_mechanics(hybrid: bool, phrase: bool) -> String {
    join_sections([SERVER_BASE, retrieval_mode_sentence(hybrid, phrase)])
}

/// Compose one tool's final description: its compiled base, the
/// phrase-syntax sentence when applicable, then the KB's extension for that
/// tool. Returns `None` for a name outside [`TOOL_NAMES`].
pub fn compose_tool_description(
    tool: &str,
    phrase_effective: bool,
    extension: Option<&str>,
) -> Option<String> {
    let base = compiled_tool_base(tool)?;
    let phrase_sentence = (tool == "search" && phrase_effective).then_some(PHRASE_SYNTAX_SENTENCE);
    Some(join_sections(
        std::iter::once(base)
            .chain(phrase_sentence)
            .chain(extension),
    ))
}

/// Append a KB extension (category 3) onto an already-composed base (server
/// instructions after `build_instructions`, or a tool's compiled+config-derived
/// description). A no-op when `extension` is `None` or blank.
pub fn append_extension(base: &str, extension: Option<&str>) -> String {
    join_sections(std::iter::once(base).chain(extension))
}

/// Every tool's composed description, keyed by tool name — the exact map
/// installed into `KbSearchServer`'s description overlay. `extensions_dir`
/// should already be resolved (see [`resolve_extensions_dir`]) so a caller
/// that also needs the server's `server.md` extension resolves the
/// directory only once per call.
pub fn compose_tool_descriptions(
    extensions_dir: Option<&Path>,
    phrase_effective: bool,
) -> HashMap<String, String> {
    TOOL_NAMES
        .iter()
        .filter_map(|&tool| {
            let extension = load_tool_extension(extensions_dir, tool);
            compose_tool_description(tool, phrase_effective, extension.as_deref())
                .map(|desc| (tool.to_string(), desc))
        })
        .collect()
}

/// Which of a KB's `server.md` extension file and the deprecated
/// `mcp.instructions` setting wins when composing server instructions. The
/// file always wins when both are present — see [`log_instructions_deprecation`]
/// for the one-time startup log that reports which case applied.
pub fn effective_server_extension(
    file_extension: Option<String>,
    legacy_instructions: Option<&str>,
) -> Option<String> {
    file_extension.or_else(|| legacy_instructions.map(str::to_string))
}

/// Log, once, whether the deprecated `mcp.instructions` setting is doing
/// anything. Intended to be called once at server startup with the
/// startup-resolved extension-file presence; a later `POST /admin/reload`
/// does not re-trigger this (same "once at startup" contract as
/// [`log_absolute_extensions_path_advisory`]) — the periodic refresh
/// recomposes instructions on every tick without re-logging this.
pub fn log_instructions_deprecation(
    legacy_instructions: Option<&str>,
    file_present: bool,
    extensions_path: &str,
) {
    if legacy_instructions.is_none() {
        return;
    }
    if file_present {
        warn!(
            "mcp.instructions is deprecated and ignored: {extensions_path}/server.md is \
             present in the knowledge base and wins."
        );
    } else {
        warn!(
            "mcp.instructions is deprecated; move its text to {extensions_path}/server.md \
             so the knowledge base can edit its own policy narrative without a restart."
        );
    }
}

/// Log, once, that an absolute `mcp.extensions_path` is accepted but not
/// reachable through `write_document` — only paths under the knowledge base
/// root are. Intended to be called once at server startup; a later reload
/// that changes this value does not re-trigger it.
pub fn log_absolute_extensions_path_advisory(extensions_path: &str) {
    if !extensions_path.is_empty() && Path::new(extensions_path).is_absolute() {
        warn!(
            extensions_path,
            "mcp.extensions_path is absolute; its MCP description extension files live \
             outside the knowledge base and are not editable through write_document."
        );
    }
}

/// Resolve `mcp.extensions_path` to an absolute directory, or `None` when
/// extension loading is disabled (empty string) or a relative value escapes
/// the data root (rejected and logged).
///
/// A relative value resolves against `data_root` via the same
/// [`crate::write::resolve_safe_write_path`] the write tools use — which is
/// what makes the extension files editable through `write_document` in the
/// first place. An absolute value is accepted as-is; see
/// [`log_absolute_extensions_path_advisory`] for the one-time advisory that
/// goes with it.
pub fn resolve_extensions_dir(data_root: &Path, extensions_path: &str) -> Option<PathBuf> {
    if extensions_path.is_empty() {
        return None;
    }
    let candidate = Path::new(extensions_path);
    if candidate.is_absolute() {
        return Some(candidate.to_path_buf());
    }
    match crate::write::resolve_safe_write_path(data_root, extensions_path) {
        Ok(p) => Some(p),
        Err(e) => {
            warn!(
                extensions_path,
                error = %e,
                "mcp.extensions_path escapes the knowledge base root; MCP description \
                 extensions disabled until this is fixed"
            );
            None
        }
    }
}

/// Read one extension file's body, degrading to `None` (compiled base
/// alone) on any missing/unreadable/non-UTF-8 file. This loader must never
/// fail startup or a refresh tick, whatever is (or isn't) in the KB.
fn read_extension_body(path: &Path) -> Option<String> {
    // The knowledge base is a synced git repo, and git materializes tracked
    // symlinks on checkout, so a hostile upstream commit could place a
    // symlink here pointing at any process-readable file (state.db, a
    // credential, /proc/self/environ) and have its contents folded straight
    // into the MCP instructions sent to every connected client. Refuse to
    // read through a symlink, the same policy `ingest.rs`'s directory walk
    // already enforces for indexed content.
    if is_symlink(path) {
        warn!(
            path = %path.display(),
            "Skipping symlink: MCP description extension path is a symlink; using compiled base only"
        );
        return None;
    }
    let bytes = match std::fs::read(path) {
        Ok(b) => b,
        Err(e) if e.kind() == std::io::ErrorKind::NotFound => {
            debug!(path = %path.display(), "no MCP description extension at this path");
            return None;
        }
        Err(e) => {
            warn!(
                path = %path.display(),
                error = %e,
                "failed to read MCP description extension; using compiled base only"
            );
            return None;
        }
    };
    let content = match String::from_utf8(bytes) {
        Ok(s) => s,
        Err(e) => {
            warn!(
                path = %path.display(),
                error = %e,
                "MCP description extension is not valid UTF-8; using compiled base only"
            );
            return None;
        }
    };

    // These files are indexed KB documents and carry frontmatter to satisfy
    // the KB's own schema; only the body may ever reach a tool description.
    let (_frontmatter, body) = crate::validate::parse_frontmatter_raw(&content);
    Some(cap_extension_body(body.trim(), path))
}

/// Enforce [`MAX_EXTENSION_BODY_BYTES`], truncating on a char boundary and
/// warning with both sizes when it actually cuts anything.
fn cap_extension_body(body: &str, path: &Path) -> String {
    if body.len() <= MAX_EXTENSION_BODY_BYTES {
        return body.to_string();
    }
    let mut end = MAX_EXTENSION_BODY_BYTES;
    while end > 0 && !body.is_char_boundary(end) {
        end -= 1;
    }
    warn!(
        path = %path.display(),
        original_bytes = body.len(),
        truncated_bytes = end,
        "MCP description extension exceeds {MAX_EXTENSION_BODY_BYTES} bytes; truncating"
    );
    body[..end].to_string()
}

/// Load the `server.md` extension body from `extensions_dir`, if any.
pub fn load_server_extension(extensions_dir: Option<&Path>) -> Option<String> {
    read_extension_body(&extensions_dir?.join("server.md"))
}

/// Load a tool's extension body (`tools/<tool>.md`) from `extensions_dir`, if any.
pub fn load_tool_extension(extensions_dir: Option<&Path>, tool: &str) -> Option<String> {
    let tools_dir = extensions_dir?.join("tools");
    // Guard the intermediate `tools/` component too, not just the leaf file:
    // a symlinked directory would let every `tools/<tool>.md` read escape the
    // extensions root just as effectively as a symlinked leaf file would.
    if is_symlink(&tools_dir) {
        warn!(
            path = %tools_dir.display(),
            "Skipping symlink: MCP description extension path is a symlink; using compiled base only"
        );
        return None;
    }
    read_extension_body(&tools_dir.join(format!("{tool}.md")))
}

/// True if `path`'s leaf component is itself a symlink (not following it).
/// A nonexistent or otherwise unstattable path is not a symlink for this
/// check's purposes — `read_extension_body`'s subsequent `std::fs::read`
/// handles the missing/unreadable cases and degrades the same way it always
/// has.
fn is_symlink(path: &Path) -> bool {
    std::fs::symlink_metadata(path)
        .map(|m| m.file_type().is_symlink())
        .unwrap_or(false)
}

#[cfg(test)]
mod tests {
    use super::*;

    // --- compiled bases ------------------------------------------------

    #[test]
    fn compiled_base_loads_for_every_tool() {
        for tool in TOOL_NAMES {
            let base = compiled_tool_base(tool);
            assert!(base.is_some(), "no compiled base for tool '{tool}'");
            assert!(
                !base.unwrap().trim().is_empty(),
                "compiled base for '{tool}' is blank"
            );
        }
    }

    #[test]
    fn compiled_base_is_none_for_unknown_tool() {
        assert!(compiled_tool_base("not_a_real_tool").is_none());
    }

    #[test]
    fn server_base_is_nonempty_and_does_not_assert_hybrid_fusion() {
        assert!(!SERVER_BASE.trim().is_empty());
        // The hybrid-fusion claim must live in `retrieval_mode_sentence`, not
        // the compiled file, since it's false when `search.hybrid` is off.
        assert!(
            !SERVER_BASE.to_lowercase().contains("fuses"),
            "server.md must not assert hybrid fusion — that's config-dependent now"
        );
    }

    // --- composition order / append rules ------------------------------

    #[test]
    fn extension_appends_after_base_with_blank_line() {
        let desc = compose_tool_description("get_schema", false, Some("Extra KB policy.")).unwrap();
        let base = compiled_tool_base("get_schema").unwrap().trim();
        assert!(desc.starts_with(base));
        assert!(desc.ends_with("Extra KB policy."));
        assert!(desc.contains("\n\n"));
    }

    #[test]
    fn missing_extension_yields_base_alone() {
        let desc = compose_tool_description("delete_document", false, None).unwrap();
        assert_eq!(desc, compiled_tool_base("delete_document").unwrap().trim());
    }

    #[test]
    fn compose_tool_description_unknown_tool_is_none() {
        assert!(compose_tool_description("bogus", false, None).is_none());
    }

    #[test]
    fn append_extension_is_noop_for_none_or_blank() {
        let base = "Base text.";
        assert_eq!(append_extension(base, None), base);
        assert_eq!(append_extension(base, Some("   ")), base);
        assert_eq!(append_extension(base, Some("More.")), "Base text.\n\nMore.");
    }

    #[test]
    fn join_sections_trims_trailing_whitespace() {
        let joined = join_sections(["a", "b  \n\n"]);
        assert_eq!(joined, "a\n\nb");
    }

    // --- search's phrase-syntax sentence, gated --------------------------

    #[test]
    fn search_description_includes_phrase_syntax_only_when_effective() {
        let with_phrase = compose_tool_description("search", true, None).unwrap();
        let without_phrase = compose_tool_description("search", false, None).unwrap();
        assert!(with_phrase.contains("double quotes"));
        assert!(!without_phrase.contains("double quotes"));
    }

    #[test]
    fn non_search_tools_never_get_the_phrase_sentence() {
        let desc = compose_tool_description("get_document", true, None).unwrap();
        assert!(!desc.contains("double quotes"));
    }

    // --- the four hybrid x phrase combinations --------------------------

    #[test]
    fn all_four_retrieval_mode_combinations_are_distinct_and_correct() {
        let tt = retrieval_mode_sentence(true, true);
        let tf = retrieval_mode_sentence(true, false);
        let ft = retrieval_mode_sentence(false, true);
        let ff = retrieval_mode_sentence(false, false);

        // All four distinct sentences.
        let all = [tt, tf, ft, ff];
        for i in 0..all.len() {
            for j in (i + 1)..all.len() {
                assert_ne!(all[i], all[j], "combinations must be distinct");
            }
        }

        assert!(tt.contains("fuses") && tt.contains("phrase"));
        assert!(tf.contains("fuses") && !tf.contains("phrase"));
        assert!(!ft.contains("fuses") && ft.contains("phrase"));
        assert!(!ff.contains("fuses") && !ff.contains("phrase"));
    }

    #[test]
    fn compose_server_mechanics_includes_the_retrieval_mode_sentence() {
        let mechanics = compose_server_mechanics(false, false);
        assert!(mechanics.contains(retrieval_mode_sentence(false, false)));
        assert!(mechanics.starts_with(SERVER_BASE.trim()));
    }

    // --- KB extension loading: frontmatter stripping, degradation -------

    #[test]
    fn frontmatter_is_stripped_and_never_appears_in_output() {
        let tmp = tempfile::tempdir().unwrap();
        std::fs::write(
            tmp.path().join("server.md"),
            "---\nstatus: active\ntype: reference\nsecret_tag: should-not-leak\n---\n\
             This is the real policy body.\n",
        )
        .unwrap();

        let body = load_server_extension(Some(tmp.path())).unwrap();
        assert!(body.contains("This is the real policy body."));
        assert!(!body.contains("secret_tag"));
        assert!(!body.contains("---"));
    }

    #[test]
    fn missing_extension_file_yields_none() {
        let tmp = tempfile::tempdir().unwrap();
        assert!(load_server_extension(Some(tmp.path())).is_none());
        assert!(load_tool_extension(Some(tmp.path()), "search").is_none());
    }

    #[test]
    fn no_extensions_dir_yields_none() {
        assert!(load_server_extension(None).is_none());
    }

    #[test]
    fn frontmatter_only_extension_degrades_to_an_empty_body() {
        // A file that's all frontmatter and no body must not surface as `None`
        // (that would be indistinguishable from a missing/unreadable file in
        // logs) — it degrades to an empty string, which `append_extension`/
        // `join_sections` already treat as a no-op (see
        // `append_extension_is_noop_for_none_or_blank`).
        let tmp = tempfile::tempdir().unwrap();
        std::fs::write(
            tmp.path().join("server.md"),
            "---\nstatus: active\ntype: reference\n---\n",
        )
        .unwrap();

        assert_eq!(load_server_extension(Some(tmp.path())).as_deref(), Some(""));
    }

    #[test]
    fn pure_whitespace_extension_degrades_to_an_empty_body() {
        // A file with no frontmatter delimiters at all, and nothing but
        // whitespace, must degrade the same way: `Some("")`, not `None` and not
        // a body full of blank lines.
        let tmp = tempfile::tempdir().unwrap();
        std::fs::write(tmp.path().join("server.md"), "   \n\n\t \n").unwrap();

        assert_eq!(load_server_extension(Some(tmp.path())).as_deref(), Some(""));
    }

    #[test]
    fn unreadable_or_unparseable_extension_yields_none() {
        let tmp = tempfile::tempdir().unwrap();
        // Invalid UTF-8 bytes: `read_to_string`/`String::from_utf8` reject this,
        // which is this loader's stand-in for "unparseable" — the frontmatter
        // parser itself is lenient by design and does not error on malformed
        // YAML, so a byte-level decode failure is the realistic failure mode.
        std::fs::write(tmp.path().join("server.md"), [0xFF, 0xFE, 0xFD]).unwrap();
        assert!(load_server_extension(Some(tmp.path())).is_none());
    }

    #[test]
    fn oversized_extension_is_truncated() {
        let tmp = tempfile::tempdir().unwrap();
        let huge = "x".repeat(MAX_EXTENSION_BODY_BYTES + 500);
        std::fs::write(tmp.path().join("server.md"), &huge).unwrap();

        let body = load_server_extension(Some(tmp.path())).unwrap();
        assert!(body.len() <= MAX_EXTENSION_BODY_BYTES);
        assert!(body.len() < huge.len());
    }

    #[test]
    fn tool_extension_path_is_tools_subdir() {
        let tmp = tempfile::tempdir().unwrap();
        std::fs::create_dir_all(tmp.path().join("tools")).unwrap();
        std::fs::write(tmp.path().join("tools/search.md"), "Search policy body.").unwrap();

        assert_eq!(
            load_tool_extension(Some(tmp.path()), "search").as_deref(),
            Some("Search policy body.")
        );
    }

    // --- symlink refusal on the read path --------------------------------

    #[test]
    fn symlinked_server_extension_is_refused() {
        let tmp = tempfile::tempdir().unwrap();
        let target = tmp.path().join("real_target.md");
        std::fs::write(&target, "Secret content that must not leak.").unwrap();
        std::os::unix::fs::symlink(&target, tmp.path().join("server.md")).unwrap();

        assert!(
            load_server_extension(Some(tmp.path())).is_none(),
            "a symlinked server.md must be refused, not read through"
        );
    }

    #[test]
    fn symlinked_tool_extension_leaf_is_refused() {
        let tmp = tempfile::tempdir().unwrap();
        std::fs::create_dir_all(tmp.path().join("tools")).unwrap();
        let target = tmp.path().join("real_target.md");
        std::fs::write(&target, "Secret content that must not leak.").unwrap();
        std::os::unix::fs::symlink(&target, tmp.path().join("tools/search.md")).unwrap();

        assert!(
            load_tool_extension(Some(tmp.path()), "search").is_none(),
            "a symlinked tools/<tool>.md must be refused, not read through"
        );
    }

    #[test]
    fn symlinked_tools_directory_is_refused() {
        let tmp = tempfile::tempdir().unwrap();
        let real_tools_dir = tmp.path().join("real_tools");
        std::fs::create_dir_all(&real_tools_dir).unwrap();
        std::fs::write(real_tools_dir.join("search.md"), "Secret content.").unwrap();
        std::os::unix::fs::symlink(&real_tools_dir, tmp.path().join("tools")).unwrap();

        assert!(
            load_tool_extension(Some(tmp.path()), "search").is_none(),
            "a symlinked tools/ intermediate directory must be refused, not walked through"
        );
    }

    // --- extensions_path resolution -------------------------------------

    #[test]
    fn empty_extensions_path_disables_loading() {
        let tmp = tempfile::tempdir().unwrap();
        assert!(resolve_extensions_dir(tmp.path(), "").is_none());
    }

    #[test]
    fn relative_extensions_path_resolves_under_data_root() {
        let tmp = tempfile::tempdir().unwrap();
        let canonical = tmp.path().canonicalize().unwrap();
        let resolved = resolve_extensions_dir(&canonical, "meta/mcp").unwrap();
        assert_eq!(resolved, canonical.join("meta/mcp"));
    }

    #[test]
    fn absolute_extensions_path_is_accepted_as_is() {
        let tmp = tempfile::tempdir().unwrap();
        let canonical = tmp.path().canonicalize().unwrap();
        let abs = canonical.join("elsewhere/mcp");
        let resolved = resolve_extensions_dir(&canonical, abs.to_str().unwrap()).unwrap();
        assert_eq!(resolved, abs);
    }

    #[test]
    fn relative_extensions_path_escaping_root_is_rejected() {
        let tmp = tempfile::tempdir().unwrap();
        let canonical = tmp.path().canonicalize().unwrap();
        assert!(resolve_extensions_dir(&canonical, "../../etc").is_none());
    }

    // --- mcp.instructions deprecation fallback ---------------------------

    #[test]
    fn file_wins_over_legacy_instructions_when_both_present() {
        let effective = effective_server_extension(
            Some("From the file.".to_string()),
            Some("From mcp.instructions."),
        );
        assert_eq!(effective.as_deref(), Some("From the file."));
    }

    #[test]
    fn legacy_instructions_used_when_no_file_present() {
        let effective = effective_server_extension(None, Some("From mcp.instructions."));
        assert_eq!(effective.as_deref(), Some("From mcp.instructions."));
    }

    #[test]
    fn neither_present_yields_none() {
        assert!(effective_server_extension(None, None).is_none());
    }

    // --- compose_tool_descriptions covers every tool --------------------

    #[test]
    fn compose_tool_descriptions_covers_every_tool() {
        let overlay = compose_tool_descriptions(None, false);
        assert_eq!(overlay.len(), TOOL_NAMES.len());
        for tool in TOOL_NAMES {
            assert!(
                overlay.contains_key(tool),
                "missing overlay entry for '{tool}'"
            );
        }
    }

    #[test]
    fn compose_tool_descriptions_appends_each_tools_own_extension() {
        let tmp = tempfile::tempdir().unwrap();
        std::fs::create_dir_all(tmp.path().join("tools")).unwrap();
        std::fs::write(tmp.path().join("tools/search.md"), "Search-only note.").unwrap();
        std::fs::write(
            tmp.path().join("tools/get_document.md"),
            "get_document-only note.",
        )
        .unwrap();

        let overlay = compose_tool_descriptions(Some(tmp.path()), false);
        assert!(overlay["search"].ends_with("Search-only note."));
        assert!(overlay["get_document"].ends_with("get_document-only note."));
        assert!(!overlay["search"].contains("get_document-only note."));
        assert!(!overlay["delete_document"].contains("note."));
    }
}
